follow bip174 spec updates: an input can have both nonWitnessUtxo and witnessUtxo
bitcoinjs/bip174 pull request #20
Opened 2020-08-19 09:39 UTC by soralit

As per https://github.com/bitcoin/bips/commit/5ac2cb5b93bf2ac1f1dac7337d93176a5edadd97 and https://github.com/bitcoin-core/HWI/commit/65c6de6b8a625eb272d1c0802473095093164821#diff-0d4ba12f98ef1621d8f2beed67a9ebd7, now PSBT inputs can have both nonWitnessUTXO and witnessUTXO.

2020-08-19 10:20 UTC, junderw commented
Thanks!

Please leave the same-type check as is.

We can not accept two witnessUtxos or two nonWitnessUtxos.

2020-08-19 10:35 UTC, soralit commented
@junderw fixed

2020-08-19 11:41 UTC, junderw requested changes
Not sure why Travis isn't working, but you need to fix the tests and commit built files, also format and linters must pass.

Look at the Travis config to see what it checks for until I fix Travis.

2020-08-19 13:05 UTC, junderw commented
I went ahead and fixed it for you. But you didn't enable edits from maintainers.

Please commit this, and I'll merge it.

```diff
diff --git a/src/lib/parser/fromBuffer.js b/src/lib/parser/fromBuffer.js
index bee6d4b..24af448 100644
--- a/src/lib/parser/fromBuffer.js
+++ b/src/lib/parser/fromBuffer.js
@@ -182,12 +182,9 @@ function psbtFromKeyVals(
             keyVal.key,
             typeFields_1.InputTypes.NON_WITNESS_UTXO,
           );
-          if (
-            input.nonWitnessUtxo !== undefined ||
-            input.witnessUtxo !== undefined
-          ) {
+          if (input.nonWitnessUtxo !== undefined) {
             throw new Error(
-              'Format Error: Input has multiple [NON_]WITNESS_UTXO',
+              'Format Error: Input has multiple NON_WITNESS_UTXO',
             );
           }
           input.nonWitnessUtxo = convert.inputs.nonWitnessUtxo.decode(keyVal);
@@ -198,13 +195,8 @@ function psbtFromKeyVals(
             keyVal.key,
             typeFields_1.InputTypes.WITNESS_UTXO,
           );
-          if (
-            input.nonWitnessUtxo !== undefined ||
-            input.witnessUtxo !== undefined
-          ) {
-            throw new Error(
-              'Format Error: Input has multiple [NON_]WITNESS_UTXO',
-            );
+          if (input.witnessUtxo !== undefined) {
+            throw new Error('Format Error: Input has multiple WITNESS_UTXO');
           }
           input.witnessUtxo = convert.inputs.witnessUtxo.decode(keyVal);
           break;
diff --git a/src/tests/fixtures/keyValsToPsbt.js b/src/tests/fixtures/keyValsToPsbt.js
index bdefaa3..8eb10c2 100644
--- a/src/tests/fixtures/keyValsToPsbt.js
+++ b/src/tests/fixtures/keyValsToPsbt.js
@@ -70,10 +70,8 @@ exports.fixtures = [
       inputKeyVals: [
         [
           {
-            key: b('01'),
-            value: b(
-              '70aaf00800000000160014d85c2b71d0060b09c9886aeb815e50991dda124d',
-            ),
+            key: b('00'),
+            value: b('03'),
           },
           {
             key: b('00'),
@@ -83,7 +81,7 @@ exports.fixtures = [
       ],
       outputKeyVals: [],
     },
-    exception: 'Format Error: Input has multiple \\[NON_\\]WITNESS_UTXO',
+    exception: 'Format Error: Input has multiple NON_WITNESS_UTXO',
   },
   {
     data: {
@@ -91,18 +89,22 @@ exports.fixtures = [
       inputKeyVals: [
         [
           {
-            key: b('00'),
-            value: b('04'),
+            key: b('01'),
+            value: b(
+              '70aaf00800000000160014d85c2b71d0060b09c9886aeb815e50991dda124d',
+            ),
           },
           {
             key: b('01'),
-            value: b('05'),
+            value: b(
+              '70aaf00800000000160014d85c2b71d0060b09c9886aeb815e50991dda124d',
+            ),
           },
         ],
       ],
       outputKeyVals: [],
     },
-    exception: 'Format Error: Input has multiple \\[NON_\\]WITNESS_UTXO',
+    exception: 'Format Error: Input has multiple WITNESS_UTXO',
   },
   {
     data: {
diff --git a/ts_src/lib/parser/fromBuffer.ts b/ts_src/lib/parser/fromBuffer.ts
index 03c673c..1c1c662 100644
--- a/ts_src/lib/parser/fromBuffer.ts
+++ b/ts_src/lib/parser/fromBuffer.ts
@@ -213,9 +213,7 @@ export function psbtFromKeyVals(
       switch (keyVal.key[0]) {
         case InputTypes.NON_WITNESS_UTXO:
           checkKeyBuffer('input', keyVal.key, InputTypes.NON_WITNESS_UTXO);
-          if (
-            input.nonWitnessUtxo !== undefined
-          ) {
+          if (input.nonWitnessUtxo !== undefined) {
             throw new Error(
               'Format Error: Input has multiple NON_WITNESS_UTXO',
             );
@@ -224,12 +222,8 @@ export function psbtFromKeyVals(
           break;
         case InputTypes.WITNESS_UTXO:
           checkKeyBuffer('input', keyVal.key, InputTypes.WITNESS_UTXO);
-          if (
-            input.witnessUtxo !== undefined
-          ) {
-            throw new Error(
-              'Format Error: Input has multiple WITNESS_UTXO',
-            );
+          if (input.witnessUtxo !== undefined) {
+            throw new Error('Format Error: Input has multiple WITNESS_UTXO');
           }
           input.witnessUtxo = convert.inputs.witnessUtxo.decode(keyVal);
           break;
diff --git a/ts_src/tests/fixtures/keyValsToPsbt.ts b/ts_src/tests/fixtures/keyValsToPsbt.ts
index eba55f3..18dda01 100644
--- a/ts_src/tests/fixtures/keyValsToPsbt.ts
+++ b/ts_src/tests/fixtures/keyValsToPsbt.ts
@@ -69,10 +69,8 @@ export const fixtures = [
       inputKeyVals: [
         [
           {
-            key: b('01'),
-            value: b(
-              '70aaf00800000000160014d85c2b71d0060b09c9886aeb815e50991dda124d',
-            ),
+            key: b('00'),
+            value: b('03'),
           },
           {
             key: b('00'),
@@ -82,7 +80,7 @@ export const fixtures = [
       ],
       outputKeyVals: [],
     },
-    exception: 'Format Error: Input has multiple \\[NON_\\]WITNESS_UTXO',
+    exception: 'Format Error: Input has multiple NON_WITNESS_UTXO',
   },
   {
     data: {
@@ -90,18 +88,22 @@ export const fixtures = [
       inputKeyVals: [
         [
           {
-            key: b('00'),
-            value: b('04'),
+            key: b('01'),
+            value: b(
+              '70aaf00800000000160014d85c2b71d0060b09c9886aeb815e50991dda124d',
+            ),
           },
           {
             key: b('01'),
-            value: b('05'),
+            value: b(
+              '70aaf00800000000160014d85c2b71d0060b09c9886aeb815e50991dda124d',
+            ),
           },
         ],
       ],
       outputKeyVals: [],
     },
-    exception: 'Format Error: Input has multiple \\[NON_\\]WITNESS_UTXO',
+    exception: 'Format Error: Input has multiple WITNESS_UTXO',
   },
   {
     data: {
```

2020-08-19 13:06 UTC, junderw commented
The above diff is based off of `2630eac345f0eac31b08d4c778c55d62a252820b`

2020-08-20 02:06 UTC, soralit commented
@junderw Thanks, tests added and please have a review. Not sure why test not passed with tape, so I changed related syntax to make it happy.

2020-08-20 07:01 UTC, merged

2020-08-20 07:04 UTC, junderw commented
published as v2.0.0